# https://github.com/elastic/kibana-docker
# https://www.elastic.co/guide/en/kibana/5.6/_pulling_the_image.html
FROM docker.elastic.co/kibana/kibana:5.6.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
