# https://github.com/elastic/kibana-docker
# https://www.elastic.co/guide/en/kibana/5.6/_pulling_the_image.html
FROM docker.elastic.co/kibana/kibana:6.6.1

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

COPY config /usr/share/kibana/config
# COPY pipeline /usr/share/logstash/pipeline
